import type { z } from "zod";
import type * as S from "./schemas";
export type PortalConfig = z.infer<typeof S.portalSchema>;
export type TripInfo = z.infer<typeof S.tripSchema>;
export type ScheduleEvent = z.infer<typeof S.eventSchema>;
export type TideData = z.infer<typeof S.tidesSchema>;
export type TideDay = z.infer<typeof S.tideDaySchema>;
export type TidePoint = z.infer<typeof S.extremumSchema>;
export type TideCurvePoint = z.infer<typeof S.sampleSchema>;
export type ActivityWindow = z.infer<typeof S.activitySchema>;
export type ActivityRule = z.infer<typeof S.ruleSchema>;
export type FamilyVideoData = z.infer<typeof S.videosSchema>;
export type ScheduleDay = z.infer<typeof S.scheduleSchema>[number];
export type MealNight = z.infer<typeof S.mealsSchema>[number];
export type PackingItem = z.infer<typeof S.packingSchema>[number];
export type GuideEntry = z.infer<typeof S.guideSchema>[number];
export type Attendee = z.infer<typeof S.peopleSchema>[number];
export type PhotoEntry = z.infer<typeof S.photosSchema>[number];
export type TripHistoryEntry = z.infer<typeof S.historySchema>[number];
export type Tradition = z.infer<typeof S.traditionsSchema>[number];
export type HistoryMeal = NonNullable<TripHistoryEntry["meals"]>[number];
